"""Added back_populates to Reactions

Revision ID: 9c382e02dd56
Revises: 4cac83c54b12
Create Date: 2024-11-25 00:54:39.876232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c382e02dd56'
down_revision: Union[str, None] = '4cac83c54b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
