"""Added back_populates to ReactionsWebsite

Revision ID: c91bf2cb9d28
Revises: 9c382e02dd56
Create Date: 2024-11-25 00:57:45.553903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91bf2cb9d28'
down_revision: Union[str, None] = '9c382e02dd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
