"""Add photo column to Chat

Revision ID: d21f0fd044ac
Revises: 27b5ad8933e4
Create Date: 2024-11-23 12:35:17.955209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21f0fd044ac'
down_revision: Union[str, None] = '27b5ad8933e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'photo')
    # ### end Alembic commands ###
