"""Added back_populates to reactions

Revision ID: 4cac83c54b12
Revises: 9de50a6bda7a
Create Date: 2024-11-25 00:17:18.390465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cac83c54b12'
down_revision: Union[str, None] = '9de50a6bda7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
